logging.config: classpath:logback.xml
security:
    sessions: ALWAYS
zuul:
    routes:
        ui:
            url: http://ui:8081
        resource:
            url: http://resource:9005

spring:
    redis:
        host: redis
        port: 6379
        default_expire_time: 86400