server.port: 8081

spring:
    application.name: ui
    redis:
        host: redis
        port: 6379
        default_expire_time: 86400

eureka:
    client.serviceUrl.defaultZone: http://registry:8761/eureka/
#    client.serviceUrl.defaultZone: http://localhost:8761/eureka/
    instance:
        #leaseRenewalIntervalInSeconds: 5
        metadataMap.instanceId: ${spring.application.name}:${random.value}
        eureka.instance.preferIpAddress: true

ribbon.eureka.enabled: true

security:
    sessions: NEVER

logging:
    level:
        org.springframework.security: TRACE
    file: ui.log

application:
    context:
        root: "/*"