# ===================================================================
# MAX Spring Cloud Config.
# ===================================================================

# Property used on app startup to check the config server status
configserver:
    name: MAX Spring Cloud Config
    status: ${spring.cloud.config.uri}/${spring.cloud.config.label}/${spring.cloud.config.name}-${spring.cloud.config.profile}.yml/

# Default JWT secret token (to be changed in production!)
max:
    security:
        authentication:
            jwt:
                secret: my-secret-token-to-change-in-production
