logging:
    level:
        org.springframework.security: WARN
    file: resource-prod.log

spring:
    redis:
        host: redis
        port: 6379
        default_expire_time: 86400

server:
    port: 9005
    address: 0.0.0.0