server.port: 9005

spring:
    application.name: resource
    redis:
        host: redis
        port: 6379
        default_expire_time: 86400

eureka:
#    client.serviceUrl.defaultZone: http://eureka:8761/eureka/
    client.serviceUrl.defaultZone: http://registry:8761/eureka/
    instance:
        #leaseRenewalIntervalInSeconds: 5
        metadataMap.instanceId: ${spring.application.name}:${random.value}
        eureka.instance.preferIpAddress: true

ribbon.eureka.enabled: true

logging:
    level:
        org.springframework.security: TRACE
    file: ui.log

application:
    context:
        root: "/*"

logging.config: classpath:logback.xml

security:
    sessions: NEVER

app:
    version: 1.0.0
    title: "MAX Cloud Resource API"
    description: "List of todo items for the demo"

swagger:
    title: "MAX Cloud Resource API"
    description: "List of todo items for the demo"
    termsOfServiceUrl: "http://max.gov/"
    contact: "jeremy.hulick@netspective.com"
    license: "Apache 2.0"
    licenseUrl: "http://www.apache.org/licenses/LICENSE-2.0.html"